# MAE pretraining (event voxel).
defaults:
  - data: stage1_event
  - model: vit_base_mae
  - optimization: mae_default
  - data_aug: event_default
  - meta: default
  - _self_

# Base output directory for checkpoints/logs/tensorboard.
folder: outputs/train_stage1_mae

hydra:
  run:
    dir: ${folder}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
